
#Populate Build.BuildNumber variable
name: $(rev:r) 

steps:
- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 2.2.203
  inputs:
    version: 2.2.203

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    projects: '**/*Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    packagesToPack: 'MazeLib/MazeLib.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)\$(BuildConfiguration)'
    versioningScheme: byEnvVar
    versionEnvVar: VersionNuget

- task: NuGetCommand@2
  displayName: NuGet push nuget.org
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/MazeLib$(VersionNuget).nupkg;!$(Build.ArtifactStagingDirectory)/**/MazeLib*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.org'
